version: 2
updates:
  # Update Docker base images
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      base-image:
        patterns:
          - ghcr.io/hassio-addons/*

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Keep Python dependencies up to date in any Python-based add-ons
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
      - dependency-type: indirect
